### ISSUE TITLE
pa11y not working on windows 10

### ISSUE THREAD

**Issue by alleypa** [pa11y/pa11y#189]
After carefully following all the setup outlined for pa11y configuration. I can't get it to work on Window 10,  node 4.2.3. Any ideas what is going on with phantomjs. I get `Error: spawn ./node_modules/phantomjs-prebuilt/bin/phantomjs ENOENT`. No matter what I do. My current version of pa11y is 4.0.1

**Comment by rowanmanning** [comment]
Hi @alleypa, I'll try and get a Windows 10 machine or VM and debug this.

**Comment by alleypa** [comment]
Hi @rowanmanning  thanks for looking into. Using pa11y works on colleagues machines running Linux/Mac Os. But on windows 10 no joy. Hopefully you see what is going on.

**Comment by rowanmanning** [comment]
Hi @alleypa, I'm unable to replicate this unfortunately. One thing that's worth trying is installing a newer version of Pa11y. In v4.1.0 we bundled PhantomJS with the library itself so it's much easier to get running on Windows.

Let me know if installing the latest version works :)

**Comment by rowanmanning** [comment]
I'm gonna close this for now, but happy to reopen if you're still having issue :)

**Comment by jjalonso** [comment]
This is a common issue happening here on our team.

Here we have the issue too in Windows 10. 

```
[11:03:24] Starting 'pa11y'...
[11:03:24] Pa11y opened _enter-pleas_7a3b1916-bfec-44a4-a7ed-734345143ff9___1508924932145.html
{ Error: spawn ./node_modules/phantomjs-prebuilt/bin/phantomjs ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn ./node_modules/phantomjs-prebuilt/bin/phantomjs',
  path: './node_modules/phantomjs-prebuilt/bin/phantomjs',
  spawnargs:
   [ '--ignore-ssl-errors=true',
     'C:\\Repos\\ui.app\\node_modules\\node-phantom-simple\\bridge.js' ] }
C:\Repos\ui.app\gulp\pa11y.js:48
          throw error;
          ^

Error: spawn ./node_modules/phantomjs-prebuilt/bin/phantomjs ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by jjalonso** [comment]
I just check with a simple example at the command line, (No GULP):

```

node node_modules\pa11y\bin\pa11y c:\Repos\ui.app\reports\protractor\page-sources\_enter-pleas_7a3b1916-bfec-44a4-a7ed-734345143ff9___1508924932145.html Welcome to Pa11y


Error: spawn ./node_modules/phantomjs-prebuilt/bin/phantomjs ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
```
