### ISSUE TITLE
Error Opening Url and Headless Process died errors

### ISSUE THREAD

**Issue by Zoheb-hassan** [pa11y/pa11y#273]
Hi, I'm trying to set up pa11y on a linux box and i was having trouble running pa11y i started with the regular pa11y "my-url" command however i was getting the following error

`PhantomJS browser created
Error: Error opening url "https://www.python.org/" : Operation canceled
    at Object.<anonymous> (/usr/lib/node_modules/pa11y/node_modules/truffler/lib/truffler.js:154:18)
    at /usr/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

However i figured from this [Pa11y fails to run on certain URLs #166
](url) that i had to set the ssl options which i did by creating the following 
`"phantom": {
    "parameters": {
        "ssl-protocol": "any"
    }
}`

and running the command pa11y --config config.js "my_url", however post that it began reporting the Headless Process died error which looks like 

`Error: HeadlessError: Phantom Process died
    at ClientRequest.<anonymous> (/usr/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:659:12)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
`

I need help with getting this right

**Comment by rowanmanning** [comment]
Closing as this was discussed in Slack

**Comment by Zoheb-hassan** [comment]
Let me add more context to the issue created, there were couple of things that needed to get this working the environment wasn't set right i.e., the proxy and then we tried passing the proxy via config parameters e mentioned [Issue 86](https://github.com/pa11y/pa11y/issues/86), however pa11y wasn't taking it for some reason. so we finally got over by modifying the pa11y.js file located under pa11y\lib which isn't the right thing to do since a sudo update will overwrite this
