### ISSUE TITLE
Can I test npx pa11y on a local php?

### ISSUE THREAD

**Issue by gusbemacbe** [pa11y/pa11y#279]
I didn't develop my projects in HTML. I developed my projects in PHP. 

I tried to run `npx pa11y --standard "WCAG2AA" --ignore "notice;warning" /Users/username/Trabalhos/Atlética\ Unisal/sitemelhor-php/index.php `

But it gave errors:

```
Error: Error opening url "http:///Users/gusbemacbe/Trabalhos/Atlética Unisal/sitemelhor-php/index.php" : Host users not found
    at Object.<anonymous> (/Users/gusbemacbe/.npm/_npx/1169/lib/node_modules/pa11y/node_modules/truffler/lib/truffler.js:154:18)
    at /Users/gusbemacbe/.npm/_npx/1169/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (/Users/gusbemacbe/.npm/_npx/1169/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by hollsk** [comment]
Hi @gusbemacbe - thanks for using Pa11y! 

You'll need to run your php page on a local web server, and point Pa11y at the local server address instead. Pa11y uses an internal browser to check pages, so it needs to be able to "see" a webpage in the same way that a webpage user would.
