### ISSUE TITLE
Error: HeadlessError: Phantom Process died

### ISSUE THREAD

**Issue by sagar441989** [pa11y/pa11y#328]
I am trying to test the https://www.tdassurance.com/home/quote.jsp but getting the below error.
Error: HeadlessError: Phantom Process died
    at ClientRequest.<anonymous> (C:\Users\#####\AppData\Roaming\npm\node_modules\pa11y\node_modules\node-phantom-simple\node-phantom-simple.js:659:12)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by rowanmanning** [comment]
Hi @sagar441989, I don't get this issue when I run Pa11y. Could I have some more information about your environment?

The simplest way to get what I need is for you to run `pa11y --environment` and then add the output to your issue description.

**Comment by sagar441989** [comment]
@rowanmanning 
pa11y --environment https://www.tdassurance.com/tdimm/mobile-apps/
Pa11y:      4.12.1
Node.js:    6.11.0
npm:        3.10.10
PhantomJS:  2.1.1
OS:         10.0.14393 (win32)

**Comment by rowanmanning** [comment]
I'm going to close this for now, as Pa11y has moved away from PhantomJS. I wasn't able to replicate in the 4.x branch. Are you still having this issue, and if so is it possible to try upgrading to Pa11y 5?
