### ISSUE TITLE
Not able to run Pa11y on AngularJS

### ISSUE THREAD

**Issue by wiprosagar123** [pa11y/pa11y#347]
pa11y <angulerJS website>
Welcome to Pa11y

 > PhantomJS browser created
**Error: Error opening url "My URL" : Operation canceled**
    at Object.<anonymous> (C:\....\AppData\Roaming\npm\node_modules\pa11y\node_modules\truffler\lib\truffler.js:154:18)
    at C:\....\AppData\Roaming\npm\node_modules\pa11y\node_modules\node
-phantom-simple\node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (C:\..AppData\Roaming\npm\node_mo
dules\pa11y\node_modules\node-phantom-simple\node-phantom-simple.js:645:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

html tag and body tag has below information
```
<html data-ng-app="dTModule" td-ngp-lang-attr="" class="ng-scope" lang="en"><head><script type="text/javascript" src="...>
<body ng-controller="usWebController" td-ui-hide-outline="" class="ng-scope td-dashboard-background td-hide-outline"><div class="mboxDefault" id="mbox-target-global-mbox-4e6225c7617b431db729d5f6e35bb0ea" style="visibility: visible; display: block;"></div>
```

**Comment by hollsk** [comment]
Hi @wiprosagar123 - the error message tells you what the problem is.

`Error opening url "My URL" :`

"My URL" is not a valid URL string, so Pa11y isn't able to open it.

**Comment by wiprosagar123** [comment]
@hollsk  I am providing valid URL in place of  'My URL'. The URL I am using can not be shared that's why I provided sample html source
