### ISSUE TITLE
Operation canceled for pure AngularJS website

### ISSUE THREAD

**Issue by sagar441989** [pa11y/pa11y#348]
pa11y <example.com>
Welcome to Pa11y

PhantomJS browser created
Error: Error opening <example.com> : Operation canceled
at Object. (C:....\AppData\Roaming\npm\node_modules\pa11y\node_modules\truffler\lib\truffler.js:154:18)
at C:....\AppData\Roaming\npm\node_modules\pa11y\node_modules\node
-phantom-simple\node-phantom-simple.js:60:18
at IncomingMessage. (C:..AppData\Roaming\npm\node_mo
dules\pa11y\node_modules\node-phantom-simple\node-phantom-simple.js:645:9)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback (internal/process/next_tick.js:104:9)
html tag and body tag has below information

```
<html data-ng-app="dTModule" td-ngp-lang-attr="" class="ng-scope" lang="en"><head><script type="text/javascript" src="...>
<body ng-controller="usWebController" td-ui-hide-outline="" class="ng-scope td-dashboard-background 
```

**Comment by rowanmanning** [comment]
Hi @sagar441989. Could you please provide all the information output when you run `pa11y --environment`? Also this will be hard to debug if I can't run Pa11y against your _actual_ URL, is it possible to either send me that or to replicate with a new test web page?

**Comment by viabledish** [comment]
HI @rowanmanning - have the same issue as @sagar441989. Here is my output from pa22y --environment:

```
Pa11y:      4.13.2
Node.js:    6.9.2
npm:        3.10.9
PhantomJS:  2.1.1
OS:         15.6.0 (darwin)
```

And here is the output from running pa11y against my site. I don't want to paste the url here, as it's not public. 
```
Welcome to Pa11y

 > PhantomJS browser created
Error: Error opening url "https://bmo-qa.rewardscatalogue.ca" : Operation canceled
    at Object.<anonymous> (/usr/local/lib/node_modules/pa11y/node_modules/truffler/lib/truffler.js:154:18)
    at /usr/local/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by josebolos** [comment]
Anyone still experiencing this problem please update to the latest version of Pa11y, which doesn't use PhantomJS any more, and check if the problem still persists.

Feel free to reopen or create a new issue if that's the case.
