### ISSUE TITLE
Puppeteer Error: Navigation failed because browser has disconnected!

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y#570]
Running pa11y on some urls (e.g. `https://chimes.cornell.edu/Chimesmasters`) causes it to fail to run randomly:

```sh
$ pa11y --debug "https://chimes.cornell.edu/Chimesmasters"

Welcome to Pa11y

 > Running Pa11y on URL https://chimes.cornell.edu/Chimesmasters
 > Debug: Launching Headless Chrome
 > Debug: Opening URL in Headless Chrome

Error: Navigation failed because browser has disconnected!
    at CDPSession.<anonymous> (/Users/jose.bolos/.nvm/versions/node/v16.1.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/LifecycleWatcher.js:46:107)
    at CDPSession.emit (node:events:365:28)
    at CDPSession._onClosed (/Users/jose.bolos/.nvm/versions/node/v16.1.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/Connection.js:215:10)
    at Connection._onClose (/Users/jose.bolos/.nvm/versions/node/v16.1.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/Connection.js:138:15)
    at WebSocket.<anonymous> (/Users/jose.bolos/.nvm/versions/node/v16.1.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/WebSocketTransport.js:48:22)
    at WebSocket.onClose (/Users/jose.bolos/.nvm/versions/node/v16.1.0/lib/node_modules/pa11y/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (node:events:365:28)
    at WebSocket.emitClose (/Users/jose.bolos/.nvm/versions/node/v16.1.0/lib/node_modules/pa11y/node_modules/ws/lib/websocket.js:191:10)
    at Socket.socketOnClose (/Users/jose.bolos/.nvm/versions/node/v16.1.0/lib/node_modules/pa11y/node_modules/ws/lib/websocket.js:850:15)
    at Socket.emit (node:events:365:28)
  -- ASYNC --
    at Frame.<anonymous> (/Users/jose.bolos/.nvm/versions/node/v16.1.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/Users/jose.bolos/.nvm/versions/node/v16.1.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/Users/jose.bolos/.nvm/versions/node/v16.1.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/helper.js:112:23)
    at runPa11yTest (/Users/jose.bolos/.nvm/versions/node/v16.1.0/lib/node_modules/pa11y/lib/pa11y.js:183:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async pa11y (/Users/jose.bolos/.nvm/versions/node/v16.1.0/lib/node_modules/pa11y/lib/pa11y.js:55:19)
    at async runProgram (/Users/jose.bolos/.nvm/versions/node/v16.1.0/lib/node_modules/pa11y/bin/pa11y.js:122:19)
```

---

Reported initially in https://github.com/pa11y/pa11y-ci/issues/128

Additional examples of random failures on other projects and URLs:

* [CivicActions/accessibility#419](https://github.com/CivicActions/accessibility/pull/419)
* https://github.com/usdoj-crt/beta-ada/runs/2603206599

## Environment:

```
pa11y --environment
Pa11y:      5.3.1
Node.js:    16.1.0
npm:        7.11.2
OS:         20.3.0 (darwin)
```

**Comment by josebolos** [comment]
This is still present on the last version of Pa11y, which is now using the last version of Puppeteer available.

From my testing, this seems to be a puppeteer issue, as I can reliably replicate the problem with a puppeteer script.

It's not feasible for Pa11y to work around Puppeteer's issues. Using pa11y's `--timeout` option seems the most reasonable approach. A value of 120000 ms seems to be enough for the page to load consistently every single time.

If anyone lands on this issue because they are experiencing the same thing, I would suggest to try the following puppeteer script first. If this script fails to load the page, then this is a puppeteer issue and should be reported on the puppeteer repo.

I've reported the issue for this specific URL:
https://github.com/puppeteer/puppeteer/issues/14061

There's nothing else that we can do here, so I'm closing this issue.
