### ISSUE TITLE
Add option or error check to prevent console logs from causing fatal error

### ISSUE THREAD

**Issue by alycia-docusign** [pa11y/pa11y#634]
https://github.com/pa11y/pa11y/blob/32774f9e707ff81bf5b1f321a4c31b51b5a0b19c/lib/pa11y.js#L164

If the page being scanned is logging an object with a circular reference to the console, this line will cause this fatal error:

```
~/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/lib/pa11y.js:164
		options.log.debug(`Browser Console: args: ${JSON.stringify(message._args)}`);
		                                                 ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'BrowserContext'
    |     property '_browser' -> object with constructor 'Browser'
    --- property '_defaultContext' closes the circle
    at JSON.stringify (<anonymous>)
    at state.consoleCallback (~/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/lib/pa11y.js:164:52)
    at 
~/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (~/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at Page.emit (~/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at Page._addConsoleMessage (~/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:778:14)
    at Page._onConsoleAPI (~/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:721:14)
    at 
~/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:151:63
    at 
~/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    ```

In an ideal world, pages in production should not be logging objects like this to their browser consoles. However, this is pretty common in dev environments. This error can be avoided in pa11y by allowing this line to fail gracefully or to turn off this feature. The real-life situation I am seeing this happen with is on staging environments where debugging is happening (particularly with third-party tools) while also testing pages through CI pipelines using pa11y prior to hitting a production build.

**Comment by alycia-docusign** [comment]
Actually, this always happens with ANYTHING that gets logged to the console, Even a string. The circular reference appears to be on the `_args` object itself.

**Comment by josebolos** [comment]
Fixed in v6.2.1 which has just been published to npm. Thanks a lot for the bug report!

**Comment by alycia-docusign** [comment]
Thank you for the quick fix!
