### ISSUE TITLE
Error: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by riccardolinares** [pa11y/pa11y#649]
## Expected behaviour
I am scanning the website https://www.paramount.com/about but I am getting an error.

## Actual behaviour
error Error: Evaluation failed: TypeError: Cannot read property 'replace' of undefined
    at Object.processFormControls (__puppeteer_evaluation_script__:32:285003)
    at Object.process (__puppeteer_evaluation_script__:32:280173)
    at m (__puppeteer_evaluation_script__:32:288962)
    at c (__puppeteer_evaluation_script__:32:288568)
    at Object.c.run (__puppeteer_evaluation_script__:32:287951)
    at __puppeteer_evaluation_script__:32:286810
    at __puppeteer_evaluation_script__:32:287071
    at h (__puppeteer_evaluation_script__:32:289574)
    at __puppeteer_evaluation_script__:32:289615
    at a (__puppeteer_evaluation_script__:32:289700)
    at ExecutionContext._evaluateInternal (C:\Users\linar\Desktop\accessibility\node_modules\pa11y\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\linar\Desktop\accessibility\node_modules\pa11y\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async runPa11yTest (C:\Users\linar\Desktop\accessibility\node_modules\pa11y\lib\pa11y.js:87:18)
    at async C:\Users\linar\Desktop\accessibility\node_modules\p-timeout\index.js:50:13

## Steps to reproduce
Run a test on this website: https://www.paramount.com/about

## Environment

  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz
    Memory: 1.19 GB / 7.45 GB
  Binaries:
    Node: 16.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.9.0 - C:\Program Files\nodejs\npm.CMD
  pa11y: 6.2.3

**Comment by simonhudson** [comment]
Hey @riccardolinares, sorry to resurrect a dead thread, but would you mind sharing your solution for this please? I'm having a similar issue when running `pa11y`. I suspect it's a Puppeteer issue, but could use a point in the right direction. Thanks in advance.

**Comment by riccardolinares** [comment]
Hi @simonhudson
in my case it was related to the translations. I was translating pa11y to Italian, but the it.js inside html_codesniffer node module was not formatted well. 

I created it from scratch (starting from the en version), built using the gruntfile.js and now it works fine :)

let me know if it solved the problem.

**Comment by simonhudson** [comment]
@riccardolinares Thanks for the prompt response 👍 

Looks like mine is an issue with `html_codesniffer` as well, quite possibly caused by the same malformed file which you saw.

Inspired by [this reply to a similar issue](https://github.com/pa11y/pa11y/issues/627#issuecomment-1196678867), I ran `npm install --save-dev axe-core` and specified `axe` as my test runner, rather than the [default `htmlcs`](https://github.com/pa11y/pa11y#runners-array). It doesn't solve the problem with `html_codesniffer`, but it does seem to provide a work around.

```javascript
pa11y(url, { runners: ['axe'] })
    .then(results => {
        // Do stuff with results
    })
    .catch(error => {
        // Do stuff with error
    });
```
