### ISSUE TITLE
Custom Timeout settings is not working - script is timed out with default 30000 ms

### ISSUE THREAD

**Issue by MyProjects-Maha** [pa11y/pa11y#692]
Even though timeout is included as part of config.json, it is taking the default timeout which is 30000 ms and not 120000 ms

```json
{
    "chromeLaunchConfig": {
        "args": [
            "--no-sandbox",
            "--disable-setuid-sandbox",
            "--disable-dev-shm-usage"
        ]
    },
    "wait": 120000,
    "actions": [
        "navigate to <url>",
        "set field #SignInEmail to *****",
        "set field #feature_login_main > div.form-group.has-feedback > div > input to *****",
        "click element #btnLogin",
        "wait for url to be <url>",
        "wait for element label[class*='***'] to be visible",
        "click element ***",
        "wait for url to be <url>"
    ],
    "timeout": 120000
}
```

Output:

```console
Error: TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node-14.15/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
    at DOMWorld.waitForFunction (/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node-14.15/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:464:26)
    at Frame.waitForFunction (/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node-14.15/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:909:32)
    at Page.waitForFunction (/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node-14.15/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1339:33)
    at Object.run (/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node-14.15/lib/node_modules/pa11y/lib/action.js:223:15)
    at runAction (/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node-14.15/lib/node_modules/pa11y/lib/action.js:29:15)
    at runActionsList (/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node-14.15/lib/node_modules/pa11y/lib/pa11y.js:268:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runPa11yTest (/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node-14.15/lib/node_modules/pa11y/lib/pa11y.js:75:2)
    at async /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node-14.15/lib/node_modules/pa11y/node_modules/p-timeout/index.js:50:13

script returned exit code 1
```

**Comment by danyalaytekin** [comment]
Hi @MyProjects-Maha.  I ran this locally with your config and this was the report:

```console
Error: TimeoutError: Pa11y timed out (120000ms)
    at Timeout.<anonymous> (/Users/danyal/.nvm/versions/node/v18.18.0/lib/node_modules/pa11y/node_modules/p-timeout/index.js:39:64)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

Could your Jenkins environment, or another participant, be imposing its own timeout of 30s?

Also, please bear in mind that Pa11y 7 does require Node 18 or above, whereas you seem to be using Node 14.  This might not be relevant to the timeout issue but could help to avoid additional problems.
